appname: "GenePool"
layout: "main"
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
  JSON:
    convert_blessed: 1

serializer: JSON
session: YAML
session_dir: /tmp/dancer-sessions

plugins:
  DBIC:
    default:
      dsn: dbi:Pg:dbname=genepool
      user: genepool
      pass: G3n3PO0L
      schema_class: GenePool::DBIC
      options:
        AutoCommit: 1
        RaiseError: 1
        pg_enable_utf8: 1


